# -*- coding: utf-8 -*-
"""enviro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DJnZZ3xdfFYbsxuJteRHBqZmxgKnIeoT
"""

!pip install opendatasets

import opendatasets as op
op.download("https://www.kaggle.com/datasets/arjunprasadsarkhel/indian-city-latitude-longitude")

import pandas as pd
df = pd.read_csv("/content/indian-city-latitude-longitude/India Cities LatLng.csv")
df.shape
df.head()

import pandas as pd
import requests
from datetime import datetime

# -----------------------------
# Step 1: Load the city dataset
# -----------------------------
# Corrected file path based on directory listing
df = pd.read_csv("/content/indian-city-latitude-longitude/India Cities LatLng.csv")

# Let's pick first 5 cities for testing
test_cities = df.head(3)  # you can change the number later

# -----------------------------
# Step 2: Your OpenWeatherMap API Key
# -----------------------------
OWM_KEY = "13bd8cad6b6a28245eff4047fb57163f"  # <<--- Replace with your OpenWeatherMap API key

# -----------------------------
# Step 3: Function to call Air Pollution API
# -----------------------------
def fetch_air_pollution(lat, lon, api_key):
    url = f"http://api.openweathermap.org/data/2.5/air_pollution?lat={lat}&lon={lon}&appid={api_key}"
    resp = requests.get(url)
    if resp.status_code != 200:
        print(f"Error fetching data for {lat}, {lon}: {resp.status_code}")
        return None
    data = resp.json()
    return data

# -----------------------------
# Step 4: Test the API for a few cities
# -----------------------------
for idx, row in test_cities.iterrows():
    city = row['city']        # adjust column name if different
    lat = row['lat']     # adjust column name if different
    lon = row['lng']    # adjust column name if different

    print(f"\nFetching air pollution data for {city} ({lat}, {lon})...")
    api_data = fetch_air_pollution(lat, lon, OWM_KEY)

    if api_data:
        # Display main fields from API
        for item in api_data.get('list', []):
            dt = datetime.utcfromtimestamp(item['dt'])
            components = item['components']
            print(f"Timestamp (UTC): {dt}")
            print(f"PM2.5: {components.get('pm2_5')}, PM10: {components.get('pm10')}, NO2: {components.get('no2')}, CO: {components.get('co')}, SO2: {components.get('so2')}, O3: {components.get('o3')}")

!pip install osmnx

import pandas as pd
import requests
from datetime import datetime, UTC
import osmnx as ox

from shapely.geometry import Polygon

# -----------------------------
# Load city dataset
# -----------------------------
df = pd.read_csv("/content/indian-city-latitude-longitude/India Cities LatLng.csv")
cities = df.head(100)   # Process all cities

# -----------------------------
# API Key
# -----------------------------
API_KEY = "13bd8cad6b6a28245eff4047fb57163f"   # <-- replace with your API key

# -----------------------------
# Fetch Air Pollution Data
# -----------------------------
def get_air_quality(lat, lon):
    url = f"http://api.openweathermap.org/data/2.5/air_pollution?lat={lat}&lon={lon}&appid={API_KEY}"
    resp = requests.get(url)
    # print(f"Air pollution API response status code for {lat}, {lon}: {resp.status_code}") # Removed this line
    if resp.status_code == 200:
        return resp.json()
    return None

# -----------------------------
# Fetch Climate/Weather Data
# -----------------------------
def get_weather(lat, lon):
    # Changed to current weather endpoint for testing
    url = f"http://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={API_KEY}&units=metric"
    resp = requests.get(url)
    # print(f"Weather API response status code for {lat}, {lon}: {resp.status_code}") # Removed this line
    if resp.status_code == 200:
        return resp.json()
    return None

# -----------------------------
# Fetch OSM Features (roads, industries, dump sites, farmland)
# -----------------------------




def get_osm_features(city_name):
    features = {"road_count": None, "industrial_count": None, "dump_count": None, "farmland_count": None}
    try:
        # Define tags for the features we want to retrieve
        tags = {"highway": True,
                "landuse": ["industrial", "farmland"],
                "amenity": "waste_disposal"}

        # Fetch features using ox.features_from_place
        osm_features = ox.features_from_place(city_name, tags)

        # Count the features by type
        features["road_count"] = len(osm_features[osm_features.geom_type.isin(['LineString', 'MultiLineString'])]) # Roads are linestrings
        features["industrial_count"] = len(osm_features[osm_features['landuse'] == 'industrial'])
        features["dump_count"] = len(osm_features[osm_features['amenity'] == 'waste_disposal'])
        features["farmland_count"] = len(osm_features[osm_features['landuse'] == 'farmland'])


    except Exception as e:
        # print(f"OSM fetch failed for {city_name}: {e}")
        pass # Added pass statement to fix IndentationError
    return features



# -----------------------------
# Collect Data for Cities
# -----------------------------
all_data = []

for _, row in cities.iterrows():
    city = row['city']
    lat = row['lat']
    lon = row['lng']

    # print(f"\nFetching data for {city}...") # Removed this line

    pollution = get_air_quality(lat, lon)
    weather   = get_weather(lat, lon)
    osm_feat  = get_osm_features(city)

    if pollution and weather:
        # take first entry for pollution
        p = pollution['list'][0]
        poll_comp = p['components']
        poll_time = datetime.fromtimestamp(p['dt'], UTC)

        # take first entry for weather
        # The structure of current weather data is different from forecast data
        # Need to adjust how weather data is extracted
        w = weather # Current weather data is not a list
        main_weather = w['main']
        wind_weather = w['wind']
        clouds_weather = w['clouds']


        all_data.append({
            "city": city,
            "lat": lat,
            "lon": lon,
            "timestamp": poll_time,

            # Pollution
            "pm2_5": poll_comp['pm2_5'],
            "pm10": poll_comp['pm10'],
            "no2": poll_comp['no2'],
            "co": poll_comp['co'],
            "so2": poll_comp['so2'],
            "o3": poll_comp['o3'],

            # Weather - Adjusted for current weather data
            "temp_day": main_weather['temp'], # Using 'temp' for current temperature
            "temp_min": main_weather['temp_min'],
            "temp_max": main_weather['temp_max'],
            "humidity": main_weather['humidity'],
            "pressure": main_weather['pressure'],
            "wind_speed": wind_weather['speed'],
            "wind_deg": wind_weather.get('deg'), # 'deg' might not always be present
            "clouds": clouds_weather['all'],

            # OSM Features
            "road_count": osm_feat["road_count"],
            "industrial_count": osm_feat["industrial_count"],
            "dump_count": osm_feat["dump_count"],
            "farmland_count": osm_feat["farmland_count"]
        })

# -----------------------------
# Convert to DataFrame
# -----------------------------
final_df = pd.DataFrame(all_data)


# Save as CSV for later preprocessing
final_df.to_csv("city_air_weather_osm.csv", index=False)

print("Dataset is ready.")

